using ClassmateApi.Tests.Helpers;
using FluentAssertions;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.EntityFrameworkCore;
using ClassmateApi.Data;
using System.Net;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using Xunit;

namespace ClassmateApi.Tests.Auth;

/// <summary>
/// Integration tests that spin up the full ASP.NET Core pipeline in memory.
/// These test routing, middleware, auth, and JSON serialization end-to-end.
/// They do NOT call Google's servers — we test protected endpoints using tokens
/// generated by JwtFactory (same key/algorithm as the real UserService).
/// </summary>
public class AuthIntegrationTests : IClassFixture<WebApplicationFactory<Program>>
{
    private readonly WebApplicationFactory<Program> _factory;

    public AuthIntegrationTests(WebApplicationFactory<Program> factory)
    {
        // Override the DB and configuration so tests don't need a real Postgres
        _factory = factory.WithWebHostBuilder(builder =>
        {
            builder.ConfigureServices(services =>
            {
                // Remove the real DbContext registration
                services.RemoveAll<DbContextOptions<AppDbContext>>();
                services.RemoveAll<AppDbContext>();

                // Add an in-memory DB for integration tests
                services.AddDbContext<AppDbContext>(opts =>
                    opts.UseInMemoryDatabase("IntegrationTestDb"));
            });

            builder.UseSetting("Jwt:Secret",      JwtFactory.TestSecret);
            builder.UseSetting("Jwt:Issuer",      JwtFactory.TestIssuer);
            builder.UseSetting("Jwt:Audience",    JwtFactory.TestAudience);
            builder.UseSetting("Jwt:ExpiryHours", "1");
            builder.UseSetting("Google:ClientId", "test-client-id");
            builder.UseSetting("Frontend:Url",    "http://localhost:3000");
        });
    }

    private HttpClient CreateAuthenticatedClient(int userId = 1)
    {
        var client = _factory.CreateClient();
        var token  = JwtFactory.CreateToken(userId);
        client.DefaultRequestHeaders.Authorization =
            new AuthenticationHeaderValue("Bearer", token);
        return client;
    }

    // ─── Unauthenticated requests ──────────────────────────────────────────────

    [Fact]
    public async Task GetMe_NoToken_Returns401()
    {
        var client = _factory.CreateClient();
        var res    = await client.GetAsync("/api/classroom/me");
        res.StatusCode.Should().Be(HttpStatusCode.Unauthorized);
    }

    [Fact]
    public async Task GetCourses_NoToken_Returns401()
    {
        var client = _factory.CreateClient();
        var res    = await client.GetAsync("/api/classroom/courses");
        res.StatusCode.Should().Be(HttpStatusCode.Unauthorized);
    }

    [Fact]
    public async Task GetAssignments_NoToken_Returns401()
    {
        var client = _factory.CreateClient();
        var res    = await client.GetAsync("/api/classroom/courses/abc/assignments");
        res.StatusCode.Should().Be(HttpStatusCode.Unauthorized);
    }

    [Fact]
    public async Task UpsertSettings_NoToken_Returns401()
    {
        var client = _factory.CreateClient();
        var res    = await client.PutAsJsonAsync("/api/classroom/settings",
            new { courseId = "c1", courseName = "Math", autoSolve = true, delayMinutes = 60 });
        res.StatusCode.Should().Be(HttpStatusCode.Unauthorized);
    }

    // ─── Invalid token ─────────────────────────────────────────────────────────

    [Fact]
    public async Task GetMe_InvalidToken_Returns401()
    {
        var client = _factory.CreateClient();
        client.DefaultRequestHeaders.Authorization =
            new AuthenticationHeaderValue("Bearer", "not.a.valid.jwt");

        var res = await client.GetAsync("/api/classroom/me");
        res.StatusCode.Should().Be(HttpStatusCode.Unauthorized);
    }

    // ─── Authenticated requests ────────────────────────────────────────────────

    [Fact]
    public async Task GetMe_ValidTokenButNoUserInDb_Returns404()
    {
        // Token is valid but user ID 999 doesn't exist in the in-memory DB
        var client = CreateAuthenticatedClient(userId: 999);
        var res    = await client.GetAsync("/api/classroom/me");

        // Our ErrorHandlingMiddleware maps NotFoundException → 404
        res.StatusCode.Should().Be(HttpStatusCode.NotFound);
    }

    [Fact]
    public async Task GetMe_ValidTokenWithExistingUser_Returns200()
    {
        // Arrange — seed user into in-memory DB
        using var scope = _factory.Services.CreateScope();
        var db          = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        var user        = TestData.MakeUser(id: 10, email: "integration@example.com");
        db.Users.Add(user);
        await db.SaveChangesAsync();

        // Act
        var client = CreateAuthenticatedClient(userId: 10);
        var res    = await client.GetAsync("/api/classroom/me");

        // Assert
        res.StatusCode.Should().Be(HttpStatusCode.OK);
        var body = await res.Content.ReadFromJsonAsync<dynamic>();
        body.Should().NotBeNull();
    }

    [Fact]
    public async Task UpsertSettings_ValidTokenExistingUser_Returns204()
    {
        // Arrange
        using var scope = _factory.Services.CreateScope();
        var db          = scope.ServiceProvider.GetRequiredService<AppDbContext>();

        // Avoid duplicate if previous test already added id=11
        if (!db.Users.Any(u => u.Id == 11))
        {
            db.Users.Add(TestData.MakeUser(id: 11, email: "settings@example.com"));
            await db.SaveChangesAsync();
        }

        // Act
        var client = CreateAuthenticatedClient(userId: 11);
        var res    = await client.PutAsJsonAsync("/api/classroom/settings", new
        {
            courseId     = "course-test-1",
            courseName   = "Test Course",
            autoSolve    = true,
            delayMinutes = 60
        });

        // Assert
        res.StatusCode.Should().Be(HttpStatusCode.NoContent);
    }

    // ─── POST /api/auth/google — invalid token ──────────────────────────────────

    [Fact]
    public async Task GoogleAuth_InvalidIdToken_Returns401()
    {
        var client = _factory.CreateClient();
        var res    = await client.PostAsJsonAsync("/api/auth/google", new
        {
            idToken      = "fake-google-id-token",
            accessToken  = "fake-access-token",
            refreshToken = "fake-refresh-token"
        });

        // Google.Apis.Auth.GoogleJsonWebSignature.ValidateAsync will throw
        // InvalidJwtException → UserService → UnauthorizedAccessException → 401
        res.StatusCode.Should().Be(HttpStatusCode.Unauthorized);
    }

    [Fact]
    public async Task GoogleAuth_MissingFields_Returns400()
    {
        var client = _factory.CreateClient();
        // Send an empty object — [Required] attributes should trigger model validation
        var res = await client.PostAsJsonAsync("/api/auth/google", new { });
        res.StatusCode.Should().Be(HttpStatusCode.BadRequest);
    }

    // ─── Swagger ───────────────────────────────────────────────────────────────

    [Fact]
    public async Task SwaggerJson_Returns200InDevelopment()
    {
        var client = _factory.CreateClient();
        var res    = await client.GetAsync("/swagger/v1/swagger.json");
        res.StatusCode.Should().Be(HttpStatusCode.OK);
    }
}